


name: Generating Sphinx Documentation

on: 
  push:
    paths:
      - '**.py'



jobs:
  sphinx-auto-generate:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 2
          - run: git checkout HEAD^
        - run: |
            ls 
            cd /docs 
            ls /docs
            ls discord
            make html


