name: Sphinx Auto Documentation
run-name: ${{ github.actor }} is generating documentation
on: 
  push:
    paths:
      - '**.py'
jobs:
  sphinx-auto-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        run: |
          echo "CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)"
          echo "::set-env name=CHANGED_FILES::$CHANGED_FILES"

      - name: Print changed files
        run: |
          echo "Changed files:"
          echo "$CHANGED_FILES"