


name: Generating Sphinx Documentation

on: 
  push:
    paths:
      - '**.py'



jobs:
  sphinx-auto-generate:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - run: |
            echo $HOME
            ls 
            cd $HOME/docs 
            ls docs
            ls discord
            make html

