name: Sphinx Auto Documentation
run-name: ${{ github.actor }} is generating documentation
on: 
  push:
    paths:
      - '**.py'
jobs:
  sphinx-auto-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        run: echo "CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)"
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

      - name: Print changed files
        run: echo "Changed files: $CHANGED_FILES"