name: Sphinx Auto Documentation
run-name: ${{ github.actor }} is generating documentation
on: 
  push:
    paths:
      - '**.py'
jobs:
  sphinx-auto-generate:
    runs-on: ubuntu-latest
    steps:

        - run: echo "this is working"