name: Sphinx Auto Documentation
on: 
  push:
    paths:
      - '**.py'
jobs:
  sphinx-auto-generate:
    name: ${{ github.actor }} is generating documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yaml
          auto-activate-base: false

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: execute py script # run main.py
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            python /scripts/update_rst.py -file_name $file
          done
    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Get changed files
    #   id: changed_files
    #   run: echo "CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)"
    #   env:
    #     CHANGED_FILES: ${{ env.CHANGED_FILES }}

    # - name: Print changed files
    #   run: |
    #     echo "Changed files: $CHANGED_FILES"