


name: Generating Sphinx Documentation

on: 
  push:
    paths:
      - '**.py'

jobs:
  sphinx-auto-generate:
    steps:
      - uses: actions/checkout@v3  s
        run: |
          cd /docs/ 
          make html

