


name: Generating Sphinx Documentation

on: 
  push:
    paths:
      - '**.py'



jobs:
  sphinx-auto-generate:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            path: main
        - run: |
            ls 
            cd main/docs 
            ls main/docs
            ls discord
            make html
            

