


name: Generating Sphinx Documentation

on: 
  push:
    paths:
      - '**.py'


jobs:
  sphinx-auto-generate:
    runs-on: ubuntu-latest
    working-directory: ./main
    steps:
        - uses: actions/checkout@
        
          with:
              fetch-depth: 0
        - run: git checkout HEAD^
        - run: pwd 